# Generated by Django 5.1.4 on 2024-12-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="date",
            field=models.DateTimeField(null=True),
        ),
    ]
