# Generated by Django 5.1.4 on 2024-12-20 16:40

import transfers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers", "0003_alter_transfer_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="images",
            field=models.ImageField(
                blank=True, upload_to=transfers.models.upload_to_images
            ),
        ),
    ]
